# Docker Compose configuration for LTE Network Simulator
# Fixed version with proper volume permissions
services:
  # Main LTE simulator service
  lte-simulator:
    build: .
    container_name: lte-network-sim
    privileged: true  # Required for SDR access and network configuration
    network_mode: host  # Required for proper cellular network simulation
    volumes:
      # Mount USB devices for SDR access
      - /dev/bus/usb:/dev/bus/usb
      # Use named volumes instead of bind mounts to avoid permission issues
      - lte_data:/opt/lte-simulator/data:rw
      - lte_logs:/opt/lte-simulator/logs:rw
      - lte_config:/opt/lte-simulator/config:rw
    devices:
      # Mount all USB devices (for SDR detection)
      - /dev/bus/usb:/dev/bus/usb
    environment:
      # UHD environment variables
      - UHD_IMAGES_DIR=/usr/local/share/uhd/images
      - UHD_PKG_PATH=/usr/local/lib/uhd
      # Application environment
      - PYTHONPATH=/opt/lte-simulator/tui
      - LOG_LEVEL=INFO
      # Fix for Ubuntu 24.04 Python warnings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    restart: unless-stopped
    # Fixed entrypoint with proper permission handling
    entrypoint: |
      bash -c "
        # Ensure the lteuser owns the volume mount points
        sudo chown -R lteuser:lteuser /opt/lte-simulator/data /opt/lte-simulator/logs /opt/lte-simulator/config
        
        # Create required files with proper ownership
        touch /opt/lte-simulator/config/user_db.csv || true
        touch /opt/lte-simulator/data/subscribers.csv || true
        touch /opt/lte-simulator/logs/tui.log || true
        
        # Create CSV headers if files are empty
        if [ ! -s /opt/lte-simulator/config/user_db.csv ]; then
          echo 'imsi,key,opc,amf,sqn' > /opt/lte-simulator/config/user_db.csv
        fi
        
        if [ ! -s /opt/lte-simulator/data/subscribers.csv ]; then
          echo 'imsi,ki,opc,amf,sqn,status,created_at,last_seen,operator,notes' > /opt/lte-simulator/data/subscribers.csv
        fi
        
        # Start TUI as lteuser
        exec sudo -u lteuser python3 /opt/lte-simulator/tui/main.py
      "
    
  # Optional: Web interface for remote management
  web-interface:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: lte-web-interface
    ports:
      - "8080:8080"
    depends_on:
      - lte-simulator
    volumes:
      - lte_data:/opt/lte-simulator/data:ro
      - lte_logs:/opt/lte-simulator/logs:ro
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    profiles:
      - web  # Only start if 'web' profile is specified

volumes:
  # Persistent volumes for data storage with proper permissions
  lte_data:
    driver: local
  lte_logs:
    driver: local
  lte_config:
    driver: local
